/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FieldId = IDL.Text;
export const DurationUnit = IDL.Variant({
  'hours' : IDL.Null,
  'days' : IDL.Null,
  'minutes' : IDL.Null,
});
export const TaskId = IDL.Text;
export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : TaskId,
  'durationUnit' : DurationUnit,
  'duration' : IDL.Nat,
  'urgency' : IDL.Nat,
  'interest' : IDL.Nat,
  'value' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'completed' : IDL.Bool,
  'influence' : IDL.Nat,
  'dependencies' : IDL.Vec(TaskId),
  'fieldId' : FieldId,
});
export const Field = IDL.Record({
  'id' : FieldId,
  'avgUrgency' : IDL.Nat,
  'icon' : IDL.Text,
  'totalTaskDuration' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'color' : IDL.Text,
  'avgInterest' : IDL.Nat,
  'totalTaskCount' : IDL.Nat,
  'taskCount' : IDL.Nat,
  'avgInfluence' : IDL.Nat,
  'avgValue' : IDL.Nat,
  'totalActiveTaskDuration' : IDL.Nat,
});
export const ExportPayload = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'fields' : IDL.Vec(Field),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createField' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [FieldId], []),
  'createTask' : IDL.Func(
      [
        FieldId,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        DurationUnit,
        IDL.Vec(TaskId),
      ],
      [TaskId],
      [],
    ),
  'deleteField' : IDL.Func([FieldId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'exportUserData' : IDL.Func([], [ExportPayload], ['query']),
  'filterTasksByAttribute' : IDL.Func(
      [FieldId, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getAllFields' : IDL.Func([], [IDL.Vec(Field)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTasksByField' : IDL.Func([FieldId], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importUserData' : IDL.Func([ExportPayload], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskCompleted' : IDL.Func([TaskId], [], []),
  'moveTaskToField' : IDL.Func([TaskId, FieldId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTasks' : IDL.Func([FieldId, IDL.Text], [IDL.Vec(Task)], ['query']),
  'undoTaskCompletion' : IDL.Func([TaskId], [], []),
  'updateField' : IDL.Func([FieldId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTask' : IDL.Func(
      [
        TaskId,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        DurationUnit,
        IDL.Vec(TaskId),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FieldId = IDL.Text;
  const DurationUnit = IDL.Variant({
    'hours' : IDL.Null,
    'days' : IDL.Null,
    'minutes' : IDL.Null,
  });
  const TaskId = IDL.Text;
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : TaskId,
    'durationUnit' : DurationUnit,
    'duration' : IDL.Nat,
    'urgency' : IDL.Nat,
    'interest' : IDL.Nat,
    'value' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'completed' : IDL.Bool,
    'influence' : IDL.Nat,
    'dependencies' : IDL.Vec(TaskId),
    'fieldId' : FieldId,
  });
  const Field = IDL.Record({
    'id' : FieldId,
    'avgUrgency' : IDL.Nat,
    'icon' : IDL.Text,
    'totalTaskDuration' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'color' : IDL.Text,
    'avgInterest' : IDL.Nat,
    'totalTaskCount' : IDL.Nat,
    'taskCount' : IDL.Nat,
    'avgInfluence' : IDL.Nat,
    'avgValue' : IDL.Nat,
    'totalActiveTaskDuration' : IDL.Nat,
  });
  const ExportPayload = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'fields' : IDL.Vec(Field),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createField' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [FieldId], []),
    'createTask' : IDL.Func(
        [
          FieldId,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          DurationUnit,
          IDL.Vec(TaskId),
        ],
        [TaskId],
        [],
      ),
    'deleteField' : IDL.Func([FieldId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'exportUserData' : IDL.Func([], [ExportPayload], ['query']),
    'filterTasksByAttribute' : IDL.Func(
        [FieldId, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getAllFields' : IDL.Func([], [IDL.Vec(Field)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTasksByField' : IDL.Func([FieldId], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importUserData' : IDL.Func([ExportPayload], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskCompleted' : IDL.Func([TaskId], [], []),
    'moveTaskToField' : IDL.Func([TaskId, FieldId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTasks' : IDL.Func([FieldId, IDL.Text], [IDL.Vec(Task)], ['query']),
    'undoTaskCompletion' : IDL.Func([TaskId], [], []),
    'updateField' : IDL.Func([FieldId, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTask' : IDL.Func(
        [
          TaskId,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          DurationUnit,
          IDL.Vec(TaskId),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };