/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DurationUnit = { 'hours' : null } |
  { 'days' : null } |
  { 'minutes' : null };
export interface ExportPayload {
  'tasks' : Array<Task>,
  'fields' : Array<Field>,
}
export interface Field {
  'id' : FieldId,
  'avgUrgency' : bigint,
  'icon' : string,
  'totalTaskDuration' : bigint,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'color' : string,
  'avgInterest' : bigint,
  'totalTaskCount' : bigint,
  'taskCount' : bigint,
  'avgInfluence' : bigint,
  'avgValue' : bigint,
  'totalActiveTaskDuration' : bigint,
}
export type FieldId = string;
export interface Task {
  'id' : TaskId,
  'durationUnit' : DurationUnit,
  'duration' : bigint,
  'urgency' : bigint,
  'interest' : bigint,
  'value' : bigint,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'completed' : boolean,
  'influence' : bigint,
  'dependencies' : Array<TaskId>,
  'fieldId' : FieldId,
}
export type TaskId = string;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createField' : ActorMethod<[string, string, string], FieldId>,
  'createTask' : ActorMethod<
    [
      FieldId,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      DurationUnit,
      Array<TaskId>,
    ],
    TaskId
  >,
  'deleteField' : ActorMethod<[FieldId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'exportUserData' : ActorMethod<[], ExportPayload>,
  'filterTasksByAttribute' : ActorMethod<
    [FieldId, string, bigint, bigint],
    Array<Task>
  >,
  'getAllFields' : ActorMethod<[], Array<Field>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTasksByField' : ActorMethod<[FieldId], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importUserData' : ActorMethod<[ExportPayload], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskCompleted' : ActorMethod<[TaskId], undefined>,
  'moveTaskToField' : ActorMethod<[TaskId, FieldId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTasks' : ActorMethod<[FieldId, string], Array<Task>>,
  'undoTaskCompletion' : ActorMethod<[TaskId], undefined>,
  'updateField' : ActorMethod<[FieldId, string, string, string], undefined>,
  'updateTask' : ActorMethod<
    [
      TaskId,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      DurationUnit,
      Array<TaskId>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];